# Generated by Django 5.2 on 2025-04-17 14:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_score_time_played'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-score'], 'verbose_name': 'Score', 'verbose_name_plural': 'Scores'},
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this score was recorded'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(help_text="The player's score value (must be positive)", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='time_played',
            field=models.IntegerField(default=0, help_text='Time played in seconds', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.ForeignKey(help_text='The user who achieved this score', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['-score'], name='scores_scor_score_542fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['user'], name='scores_scor_user_id_bcceec_idx'),
        ),
    ]
