# Generated by Django 4.1.3 on 2024-03-20 21:14

import logging
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations

logger = logging.getLogger('django')

User = get_user_model()


def create_development_superuser(apps, schema_editor):
    if settings.AUTH_SUPERUSER_EMAIL and settings.AUTH_SUPERUSER_PASSWORD:
        superuser = User.objects.create_superuser(
            email=settings.AUTH_SUPERUSER_EMAIL,
            password=settings.AUTH_SUPERUSER_PASSWORD, 
            first_name='Admin',
        )
        logger.info('Superuser \'{superuser}\' created.'.format(superuser=superuser))
    else:
        logger.info('Superuser not created.')


def delete_development_superuser(apps, schema_editor):
    superuser = User.objects.filter(email=settings.AUTH_SUPERUSER_EMAIL).first()
    if superuser:
        superuser.delete()
        logger.info('Superuser \'{superuser}\' deleted.'.format(superuser=superuser))
    else:
        logger.info('Superuser not found; did not delete.')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_development_superuser, delete_development_superuser),
    ]
